### ISSUE TITLE
Deprecation Warnings causing failure

### ISSUE THREAD

**Issue by ajstewart** [ska-sa/homebrew-tap#18]
A few deprecations warnings popping up that I thought were worth recording.

Edit: Which in turn seem to stop installations (which makes sense!):

```
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/casacore.rb:24:in `<class:Casacore>'
Please report this to the ska-sa/tap tap!

==> Installing casacore from ska-sa/tap
Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.

vlan-2722-10-17-246-242:~ adam-astro$ brew --version
Homebrew 1.5.4
Homebrew/homebrew-core (git revision 964b; last commit 2018-02-11)
```

```==> Tapping ska-sa/tap
Cloning into '/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap'...
remote: Counting objects: 25, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 25 (delta 0), reused 7 (delta 0), pack-reused 0
Unpacking objects: 100% (25/25), done.
Warning: Calling 'depends_on :tex' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/sketch.rb:11:in `<class:Sketch>'
Please report this to the ska-sa/tap tap!

Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/obit.rb:37:in `<class:Obit>'
Please report this to the ska-sa/tap tap!

Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/tigger.rb:8:in `<class:Tigger>'
Please report this to the ska-sa/tap tap!

Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/tigger.rb:9:in `<class:Tigger>'
Please report this to the ska-sa/tap tap!

Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/tigger.rb:10:in `<class:Tigger>'
Please report this to the ska-sa/tap tap!

Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/tigger.rb:11:in `<class:Tigger>'
Please report this to the ska-sa/tap tap!

Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/tigger.rb:12:in `<class:Tigger>'
Please report this to the ska-sa/tap tap!

Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/owlcat.rb:13:in `<class:Owlcat>'
Please report this to the ska-sa/tap tap!

Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/xpra.rb:12:in `<class:Xpra>'
Please report this to the ska-sa/tap tap!

Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/xpra.rb:14:in `<class:Xpra>'
Please report this to the ska-sa/tap tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/casarest.rb:20:in `block in <class:Casarest>'
Please report this to the ska-sa/tap tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/casarest.rb:20:in `block in <class:Casarest>'
Please report this to the ska-sa/tap tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/casarest.rb:20:in `block in <class:Casarest>'
Please report this to the ska-sa/tap tap!

Warning: Calling 'depends_on ... => :python' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/meqtrees.rb:27:in `<class:Meqtrees>'
Please report this to the ska-sa/tap tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/meqtrees.rb:62:in `block in <class:Meqtrees>'
Please report this to the ska-sa/tap tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/meqtrees.rb:62:in `block in <class:Meqtrees>'
Please report this to the ska-sa/tap tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/ska-sa/homebrew-tap/meqtrees.rb:62:in `block in <class:Meqtrees>'
Please report this to the ska-sa/tap tap!

Tapped 22 formulae (70 files, 131.4KB)
```

**Comment by ludwigschwardt** [comment]
Hi Adam, thanks for this! I've finally woken up to this issue. The latest master addresses these deprecations but the formulas probably need more work to get everything running again.

**Comment by ajstewart** [comment]
Hi, thanks for getting to this!

Might be a separate issue, but attempting to install casacore I now get the following error:

```
~ adam-astro$ brew install casacore
==> Installing casacore from ska-sa/tap
==> Downloading https://github.com/casacore/casacore/archive/v2.4.0.tar.gz
Already downloaded: /Users/adam-astro/Library/Caches/Homebrew/casacore-2.4.0.tar.gz
==> cmake ../.. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/casacore/2.4.0 -DCMAKE_BUILD_TYPE=Relea
Last 15 lines from /Users/adam-astro/Library/Logs/Homebrew/casacore/01.cmake:
-- FFTW3 library? ........ = /usr/local/lib/libfftw3f_threads.dylib;/usr/local/lib/libfftw3_threads.dylib;/usr/local/lib/libfftw3f.dylib;/usr/local/lib/libfftw3.dylib
-- BUILD_PYTHON .......... = ON
-- BUILD_PYTHON3 ......... = OFF
-- PYTHON2_EXECUTABLE ......... = /usr/local/bin/python2
-- PYTHON2_LIBRARIES........... = /usr/local/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib
-- PYTHON2_NUMPY_INCLUDE_DIRS . = /usr/local/lib/python2.7/site-packages/numpy/core/include
-- PYTHON2_Boost_LIBRARIES .... =
-- PYTHON2_Boost_INCLUDE_DIRS . = /usr/local/include
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_PYTHON_LIBRARY_DEBUG (ADVANCED)
    linked by target "tConvert" in directory /tmp/casacore-20180605-24028-1vb1vys/casacore-2.4.0/python/Converters/test

-- Configuring incomplete, errors occurred!
See also "/tmp/casacore-20180605-24028-1vb1vys/casacore-2.4.0/build/release/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ska-sa/homebrew-tap/issues
```

**Comment by ludwigschwardt** [comment]
Try the latest version - I had to pin boost-python to an older version.

**Comment by ludwigschwardt** [comment]
Yes, I've always got that warning too but it seems to work otherwise.

Great, thanks for checking this!

I'm closing the issue but feel free to reopen it if things are still wonky.
